[env:sparkfun_esp32s2_thing_plus_c]
platform = espressif32@6.12.0
board = sparkfun_esp32s2_thing_plus_c
framework = arduino, espidf
monitor_speed = 115200
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0

build_flags =
    -D USER_SETUP_LOADED=1
    -D ST7789_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MISO=19
    -D TFT_MOSI=23
    -D TFT_CS=12
    -D TFT_SCLK=18
    -D TFT_RST=-1
    -D TFT_DC=13
    -D LOAD_GLCD=1
    -D TFT_INVERSION_ON=1
    -D SPI_FREQUENCY=40000000

    -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/cores/esp32
    -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/variants/esp32
    -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/SPI/src
    -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/SD/src
    -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/FS/src

lib_deps =
    bodmer/TFT_eSPI
    bodmer/TFT_eWidget

board_build.cmake_extra_args =
    -DCMAKE_DISABLE_FIND_PACKAGE_Git=TRUE
    -DGIT_FOUND=FALSE
    -DPROJECT_VER=1.0.0

platform_packages =
    tool-cmake@3.16.4
