[env:sparkfun_esp32s2_thing_plus_c]
platform = espressif32@6.12.0
board = sparkfun_esp32s2_thing_plus_c
framework = arduino, espidf
monitor_speed = 115200

lib_deps =
    bodmer/TFT_eSPI
    bodmer/TFT_eWidget